#!/usr/bin/env python3
"""Assemble case-demonstrations.md from per-case component files.

Each case directory contains:
  - case.yaml: metadata, identity, facts, eval expression
  - fulltext.md: full court text (optional — hypothetical cases lack this)
  - summary.md: court text summary for left column
  - framework-output.md: generated framework output for right column
"""
import os
import yaml

CASES_DIR = os.path.join(os.path.dirname(__file__), "..", "docs", "civil-act", "cases")
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "docs", "civil-act", "case-demonstrations.md")

# Order of cases in the final document
CASE_ORDER = [
    "2005다71659",
    "94다12074",
    "2019다280375",
    "2013다49794",
    "98다60828",
    "91다32190",
]

CSS = """\
<style>
.comparison { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; border: 1px solid var(--md-default-fg-color--lightest); }
.comparison > div { padding: 0.5rem 1rem; }
.comparison > div:first-child { border-right: 1px solid var(--md-default-fg-color--lightest); }
.comparison-header { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; background: var(--md-default-fg-color--lightest); font-weight: bold; padding: 0.5rem 1rem; }
</style>
"""

HEADER = """\
# Case Demonstrations: Framework vs Court

Each case shows three sections:

1. **Identity** — persons and acts mapped to Haskell values
2. **Fact Translation** — case law facts mapped to framework encodings
3. **Judgment Comparison** — actual court holding vs framework output

Generated by `python3 scripts/assemble-cases.py` after `python3 scripts/generate-cases.py`.
The framework output is **purely mechanical** — once facts are mapped, no human judgment is involved.

---
"""

PIPELINE = """\
---

## Pipeline Summary

```
  인정사실 (자연어)
      │
      │  ← 인간/LLM 판단 (유일한 비기계적 단계)
      ▼
  Identity + Fact Translation (위 표)
      │
      │  ← 순수 기계적 (evaluateAll + renderJudgment)
      ▼
  프레임워크 판결문 (위 표 우측 열)
      │
      │  ← LLM 서브에이전트 (고정 지시문, 무맥락)
      ▼
  실제 판결문과의 일치도 판정 (match.yaml)
```
"""

APPENDIX = """\
---

## Appendix: Verification Methodology

### Match Verification Subagent

각 판례에 대해, 프레임워크 출력과 실제 판결문의 일치 여부를 판정하기 위해
LLM 서브에이전트를 사용하였다. 서브에이전트는 다음 조건으로 실행된다:

- **모델**: Claude (claude-opus-4-6, Claude Code Agent tool 경유)
- **제공 맥락**: 없음 (fulltext.md와 framework-output.md 두 파일만 제공)
- **지시문**: [`scripts/directives/verify-match.md`](../../scripts/directives/verify-match.md)

서브에이전트는 프로젝트 구조, Haskell 코드, 다른 판례에 대한 사전 지식 없이
오직 두 문서만을 비교하여 YAML 형식의 판정 결과를 출력한다.

### 판정 기준

- **true**: 프레임워크의 최종 판단이 법원의 판시와 본질적으로 일치
- **partial**: 일부 쟁점에서 일치하나 다른 쟁점에서 불일치
- **false**: 프레임워크의 결론이 법원의 판단과 모순

### 한계

현재 프레임워크는 민법 조문의 기본 규정만 인코딩하고 있어,
판례법에 의해 확립된 예외 법리(묵시적 동의, 상대방 동일시 등)를
반영하지 못한다. 이는 향후 확장 과제이다.
"""


def read_file(path: str) -> str | None:
    if os.path.isfile(path):
        with open(path, "r") as f:
            return f.read().strip()
    return None


def identity_grid(case_data: dict) -> str:
    """Build identity section as a markdown table with id, role, haskell."""
    rows = case_data.get("identity", [])
    if not rows:
        return ""
    lines = []
    lines.append("| ID | 역할 | Haskell |")
    lines.append("|:---|:-----|:--------|")
    for row in rows:
        rid = row.get("id", "")
        role = row.get("role", "")
        haskell = row.get("haskell", "")
        lines.append(f"| `{rid}` | {role} | `{haskell}` |")
    return "\n".join(lines)


def facts_grid(case_data: dict) -> str:
    """Build fact translation section as a side-by-side grid."""
    rows = case_data.get("facts", [])
    if not rows:
        return ""
    lines = []
    lines.append('<div class="comparison-header">')
    lines.append("<div>인정사실</div>")
    lines.append("<div>Haskell Encoding</div>")
    lines.append("</div>")
    lines.append('<div class="comparison" markdown>')
    lines.append("<div markdown>")
    lines.append("")
    for row in rows:
        lines.append(f"- {row['description']}")
    lines.append("")
    lines.append("</div>")
    lines.append("<div markdown>")
    lines.append("")
    for row in rows:
        lines.append(f"- `{row['haskell']}`")
    lines.append("")
    lines.append("</div>")
    lines.append("</div>")
    return "\n".join(lines)


def judgment_grid(case_data: dict, summary: str, framework: str) -> str:
    """Build judgment comparison as a side-by-side grid."""
    court = case_data.get("court") or "(판례 미매칭)"
    lines = []
    lines.append('<div class="comparison-header">')
    lines.append(f"<div>{court}</div>")
    lines.append("<div>프레임워크 출력</div>")
    lines.append("</div>")
    lines.append('<div class="comparison" markdown>')
    lines.append("<div markdown>")
    lines.append("")
    lines.append(summary)
    lines.append("")
    lines.append("</div>")
    lines.append("<div markdown>")
    lines.append("")
    lines.append(framework)
    lines.append("")
    lines.append("</div>")
    lines.append("</div>")
    return "\n".join(lines)


def match_badge(case_dir: str) -> str:
    """Read match.yaml and return a badge string, or empty if no match file."""
    match_path = os.path.join(case_dir, "match.yaml")
    if not os.path.isfile(match_path):
        return ""
    with open(match_path, "r") as f:
        data = yaml.safe_load(f)
    if not data:
        return ""
    result = data.get("match", "")
    reasoning = data.get("reasoning", "")
    if result is True or result == "true":
        icon = "&#x2705;"  # green check
        label = "일치"
    elif result == "partial":
        icon = "&#x26A0;"  # warning
        label = "부분 일치"
    else:
        icon = "&#x274C;"  # red X
        label = "불일치"
    return f"**판정**: {icon} {label} — {reasoning}"


def build_case(case_name: str, case_num: int) -> str:
    """Build the markdown section for a single case."""
    case_dir = os.path.join(os.path.abspath(CASES_DIR), case_name)
    yaml_path = os.path.join(case_dir, "case.yaml")

    with open(yaml_path, "r") as f:
        case_data = yaml.safe_load(f)

    title = case_data.get("title", case_name)
    court = case_data.get("court")
    section = case_data.get("section", "")

    summary = read_file(os.path.join(case_dir, "summary.md")) or "(요약 없음)"
    framework = read_file(os.path.join(case_dir, "framework-output.md")) or "(프레임워크 출력 없음)"

    # Section heading
    if court:
        heading = f"## Case {case_num}: {title} ({court})"
    else:
        heading = f"## Case {case_num}: {title}"

    lines = [heading, ""]

    # Link to fulltext if it exists
    has_fulltext = os.path.isfile(os.path.join(case_dir, "fulltext.md"))
    if has_fulltext and court:
        lines.append(f"[판결문 전문](cases/{case_name}/fulltext.md)")
        lines.append("")

    # Match badge (only for real court cases)
    badge = match_badge(case_dir)
    if badge:
        lines.append(badge)
        lines.append("")

    # Identity grid
    lines.append("### Identity")
    lines.append("")
    lines.append(identity_grid(case_data))
    lines.append("")

    # Facts grid
    lines.append("### Fact Translation")
    lines.append("")
    lines.append(facts_grid(case_data))
    lines.append("")

    # Judgment comparison grid
    lines.append("### Judgment Comparison")
    lines.append("")
    lines.append(judgment_grid(case_data, summary, framework))
    lines.append("")

    return "\n".join(lines)


def main():
    parts = [CSS, HEADER]
    for i, case_name in enumerate(CASE_ORDER, 1):
        case_dir = os.path.join(os.path.abspath(CASES_DIR), case_name)
        if not os.path.isdir(case_dir):
            print(f"Warning: case directory not found: {case_name}")
            continue
        parts.append(build_case(case_name, i))
        parts.append("---\n")

    parts.append(PIPELINE)
    parts.append(APPENDIX)

    output = os.path.abspath(OUTPUT)
    with open(output, "w") as f:
        f.write("\n".join(parts))

    print(f"Assembled: {output}")
    print(f"Cases: {len(CASE_ORDER)}")


if __name__ == "__main__":
    main()
