#!/usr/bin/env python3
"""Assemble case-demonstrations.md from per-case component files.

Each case directory contains:
  - case.yaml: metadata, identity, facts, eval expression
  - fulltext.md: full court text (optional — hypothetical cases lack this)
  - summary.md: court text summary for left column
  - framework-output.md: generated framework output for right column
"""
import os
import yaml

CASES_DIR = os.path.join(os.path.dirname(__file__), "..", "docs", "civil-act", "cases")
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "docs", "civil-act", "case-demonstrations.md")

# Order of cases in the final document
CASE_ORDER = [
    "2005다71659",
    "94다12074",
    "2019다280375",
    "2013다49794",
    "98다60828",
    "91다32190",
]

CSS = """\
<style>
.comparison { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; border: 1px solid var(--md-default-fg-color--lightest); }
.comparison > div { padding: 0.5rem 1rem; }
.comparison > div:first-child { border-right: 1px solid var(--md-default-fg-color--lightest); }
.comparison-header { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; background: var(--md-default-fg-color--lightest); font-weight: bold; padding: 0.5rem 1rem; }
</style>
"""

HEADER = """\
# Case Demonstrations: Framework vs Court

Each case shows three sections:

1. **Identity** — persons and acts mapped to Haskell values
2. **Fact Translation** — case law facts mapped to framework encodings
3. **Judgment Comparison** — actual court holding vs framework output

Generated by `python3 scripts/assemble-cases.py` after `python3 scripts/generate-cases.py`.
The framework output is **purely mechanical** — once facts are mapped, no human judgment is involved.

---
"""

PIPELINE = """\
## Pipeline Summary

```
  Recognized facts (natural language)
      │
      │  ← Human/LLM judgment (the only non-mechanical step)
      ▼
  Identity + Fact Translation (tables above)
      │
      │  ← Purely mechanical (evaluateAll + renderJudgment)
      ▼
  Framework output (right column above)
      │
      │  ← LLM subagent (fixed directive, zero context)
      ▼
  Match verification (match.yaml)
```
"""

ANALYSIS = """\
---

## Analysis: Current Limitations and Extensibility

### Current State

Across 6 Supreme Court cases, the framework accurately encodes **statutory
text** (조문) but does not yet reflect **case-law doctrines** (판례법리)
— judge-made exceptions established through precedent.

| Case | Match | Missing doctrine |
|:-----|:------|:-----------------|
| 2005다71659 | ⚠️ partial | Reasoning chain for §6 implied consent (처분허락) |
| 94다12074 | ⚠️ partial | Conditional judgment pending fact-finding (선의 여부) |
| 2013다49794 | ⚠️ partial | Counterparty exploitation defeats gross-negligence bar (§109 판례법리) |
| 2019다280375 | ❌ mismatch | Registration chain validity analysis (등기법 layer) |
| 98다60828 | ❌ mismatch | Agent identifiable with counterparty ≠ third party (§110②) |
| 91다32190 | ❌ mismatch | Factual-act delegation ≠ basic agency authority (§126 prerequisite) |

### What This Means

The mismatches are not **design limitations** — they are **encoding coverage
gaps**. The framework's core engine already supports the exact mechanism
needed to close them: **stratified defeasible reasoning**.

Each legal rule can override a lower layer's verdict, and the entire
override chain is preserved as a type-level proof term:

```haskell
-- Base rule application
JBase     :: Verdict → ArticleRef → Text → Judgment '[l]
-- Higher layer overrides lower layer's verdict
JOverride :: Judgment prev → Verdict → ArticleRef → Text → Judgment (l ': prev)
-- Higher layer delegates (does not override)
JDelegate :: Judgment prev → Judgment (l ': prev)
```

To close the gaps identified above:

**98다60828** — Add an `AgentIdentifiableWithCounterparty` fact. When present,
a new layer overrides §110②'s third-party fraud restriction. The existing
§110 rules remain untouched.

**2013다49794** — Add a `CounterpartyExploitedMistake` fact. When present,
a new layer overrides §109's gross-negligence bar. The existing §109 rule
remains untouched.

**91다32190** — Add a `DelegatedFactualActOnly` fact. When present,
it blocks §126 apparent authority from applying as a precondition. The
existing §126 rule remains untouched.

Each extension adds **new fact types and new layers** without modifying
existing rules. This is the defeasible reasoning engine working as designed.

### The Verification Pipeline as a Development Tool

This comparison pipeline mechanically identifies where the framework
needs to grow:

1. Encode a court case as facts
2. Generate framework output (purely mechanical)
3. A zero-context LLM compares output against the actual judgment
4. Each mismatch **is** the next doctrine to encode

Mismatch ≠ failure. Mismatch = next work item.
"""

APPENDIX = """\
---

## Appendix: Verification Methodology

### Match Verification Subagent

Each case is verified by an LLM subagent that compares the framework
output against the actual court judgment. The subagent operates under
these constraints:

- **Model**: Claude (claude-opus-4-6 via Claude Code Agent tool)
- **Context provided**: None — only `fulltext.md` and `framework-output.md`
- **Directive**: [`scripts/directives/verify-match.md`](../../scripts/directives/verify-match.md)

The subagent has no knowledge of the project architecture, Haskell code,
or any other case. It reads only the two specified files and outputs a
YAML verdict.

### Match Criteria

- **true**: Framework's final judgment essentially aligns with the court's holding
- **partial**: Alignment on some issues, divergence on others
- **false**: Framework's conclusion contradicts the court's decision
"""


def read_file(path: str) -> str | None:
    if os.path.isfile(path):
        with open(path, "r") as f:
            return f.read().strip()
    return None


def identity_grid(case_data: dict) -> str:
    """Build identity section as a markdown table with id, role, haskell."""
    rows = case_data.get("identity", [])
    if not rows:
        return ""
    lines = []
    lines.append("| ID | 역할 | Haskell |")
    lines.append("|:---|:-----|:--------|")
    for row in rows:
        rid = row.get("id", "")
        role = row.get("role", "")
        haskell = row.get("haskell", "")
        lines.append(f"| `{rid}` | {role} | `{haskell}` |")
    return "\n".join(lines)


def facts_grid(case_data: dict) -> str:
    """Build fact translation section as a side-by-side grid."""
    rows = case_data.get("facts", [])
    if not rows:
        return ""
    lines = []
    lines.append('<div class="comparison-header">')
    lines.append("<div>인정사실</div>")
    lines.append("<div>Haskell Encoding</div>")
    lines.append("</div>")
    lines.append('<div class="comparison" markdown>')
    lines.append("<div markdown>")
    lines.append("")
    for row in rows:
        lines.append(f"- {row['description']}")
    lines.append("")
    lines.append("</div>")
    lines.append("<div markdown>")
    lines.append("")
    for row in rows:
        lines.append(f"- `{row['haskell']}`")
    lines.append("")
    lines.append("</div>")
    lines.append("</div>")
    return "\n".join(lines)


def judgment_grid(case_data: dict, summary: str, framework: str) -> str:
    """Build judgment comparison as a side-by-side grid."""
    court = case_data.get("court") or "(판례 미매칭)"
    lines = []
    lines.append('<div class="comparison-header">')
    lines.append(f"<div>{court}</div>")
    lines.append("<div>프레임워크 출력</div>")
    lines.append("</div>")
    lines.append('<div class="comparison" markdown>')
    lines.append("<div markdown>")
    lines.append("")
    lines.append(summary)
    lines.append("")
    lines.append("</div>")
    lines.append("<div markdown>")
    lines.append("")
    lines.append(framework)
    lines.append("")
    lines.append("</div>")
    lines.append("</div>")
    return "\n".join(lines)


def match_badge(case_dir: str) -> str:
    """Read match.yaml and return a badge string, or empty if no match file."""
    match_path = os.path.join(case_dir, "match.yaml")
    if not os.path.isfile(match_path):
        return ""
    with open(match_path, "r") as f:
        data = yaml.safe_load(f)
    if not data:
        return ""
    result = data.get("match", "")
    reasoning = data.get("reasoning", "")
    if result is True or result == "true":
        icon = "&#x2705;"  # green check
        label = "일치"
    elif result == "partial":
        icon = "&#x26A0;"  # warning
        label = "부분 일치"
    else:
        icon = "&#x274C;"  # red X
        label = "불일치"
    return f"**판정**: {icon} {label} — {reasoning}"


def build_case(case_name: str, case_num: int) -> str:
    """Build the markdown section for a single case."""
    case_dir = os.path.join(os.path.abspath(CASES_DIR), case_name)
    yaml_path = os.path.join(case_dir, "case.yaml")

    with open(yaml_path, "r") as f:
        case_data = yaml.safe_load(f)

    title = case_data.get("title", case_name)
    court = case_data.get("court")
    section = case_data.get("section", "")

    summary = read_file(os.path.join(case_dir, "summary.md")) or "(요약 없음)"
    framework = read_file(os.path.join(case_dir, "framework-output.md")) or "(프레임워크 출력 없음)"

    # Section heading
    if court:
        heading = f"## Case {case_num}: {title} ({court})"
    else:
        heading = f"## Case {case_num}: {title}"

    lines = [heading, ""]

    # Link to fulltext if it exists
    has_fulltext = os.path.isfile(os.path.join(case_dir, "fulltext.md"))
    if has_fulltext and court:
        lines.append(f"[판결문 전문](cases/{case_name}/fulltext.md)")
        lines.append("")

    # Match badge (only for real court cases)
    badge = match_badge(case_dir)
    if badge:
        lines.append(badge)
        lines.append("")

    # Identity grid
    lines.append("### Identity")
    lines.append("")
    lines.append(identity_grid(case_data))
    lines.append("")

    # Facts grid
    lines.append("### Fact Translation")
    lines.append("")
    lines.append(facts_grid(case_data))
    lines.append("")

    # Judgment comparison grid
    lines.append("### Judgment Comparison")
    lines.append("")
    lines.append(judgment_grid(case_data, summary, framework))
    lines.append("")

    return "\n".join(lines)


def main():
    parts = [CSS, HEADER, PIPELINE]
    for i, case_name in enumerate(CASE_ORDER, 1):
        case_dir = os.path.join(os.path.abspath(CASES_DIR), case_name)
        if not os.path.isdir(case_dir):
            print(f"Warning: case directory not found: {case_name}")
            continue
        parts.append(build_case(case_name, i))
        parts.append("---\n")

    parts.append(ANALYSIS)
    parts.append(APPENDIX)

    output = os.path.abspath(OUTPUT)
    with open(output, "w") as f:
        f.write("\n".join(parts))

    print(f"Assembled: {output}")
    print(f"Cases: {len(CASE_ORDER)}")


if __name__ == "__main__":
    main()
